import { describe, it, expect } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { ProviderModeMonitorView, type ProviderModeTrace } from './ProviderModeMonitor';
// Render against the captured provider-mode trace fixture (zero-cost capture of the tool-layer
// pipeline + the verified facts of the gated (b) metered run — regenerated by
// tests/provider_mode_trace.test.ts).
import realTrace from '../../api/fixtures/provider-mode-trace.json';

const trace = realTrace as unknown as ProviderModeTrace;

describe('EPIC-035 TIER C: provider-mode monitor — read-only projection of the provider path', () => {
  it('shows the tool-layer confinement: default-deny, no Bash, core no AI SDK, + the per-tool audit', () => {
    render(<ProviderModeMonitorView trace={trace} />);
    expect(screen.getByTestId('tool-layer-status')).toBeTruthy();
    const text = screen.getByTestId('tool-layer-status').textContent || '';
    expect(text).toMatch(/default-deny/);
    expect(text).toMatch(/no shell|Bash is not/);
    expect(text).toMatch(/no AI SDK/);
    // one audit row per tool call (write_file allowed, bash refused, report allowed)
    expect(screen.getAllByTestId('tool-layer-invariant').length).toBeGreaterThanOrEqual(3);
  });

  it('shows what the real metered model did (whitelist-only, zero breaches) + the default-deny review', () => {
    render(<ProviderModeMonitorView trace={trace} />);
    const rr = screen.getByTestId('real-run-status').textContent || '';
    expect(rr).toMatch(/whitelist only/);
    expect(rr).toMatch(/breaches: 0/);
    expect(rr).toMatch(/api\.openai\.com/);
    // the default-deny review surfaces the refused unexpected tool
    const denies = screen.getAllByTestId('default-deny-item');
    expect(denies.length).toBeGreaterThanOrEqual(1);
    expect(denies[0].textContent).toMatch(/refused/);
  });

  it('shows the completion flow + exit-gate ACCEPTED verdict', () => {
    render(<ProviderModeMonitorView trace={trace} />);
    expect(screen.getAllByTestId('completion-step')).toHaveLength(5);
    expect(screen.getByTestId('exit-gate-verdict').textContent).toMatch(/ACCEPTED/);
    expect(screen.getByTestId('diff-panel').textContent).toMatch(/slugify\.mjs/);
  });

  it('is READ-ONLY — the only control replays the recorded trace; no run/spawn/execute control', () => {
    const { container } = render(<ProviderModeMonitorView trace={trace} />);
    // replay steps through existing events (read-only projection)
    const replay = screen.getByTestId('replay-step');
    fireEvent.click(replay);
    expect(screen.getAllByTestId('replay-event').length).toBeGreaterThan(0);
    // no control that could trigger execution or relax isolation
    expect(container.textContent || '').not.toMatch(/\b(spawn|execute run|start run|disable isolation|open gate)\b/i);
  });
});
